---
- hosts: localhost
  become: yes
  gather_facts: false
  vars_files: 
    - globals.yaml

  tasks:
  # Docker installation bits
  - name: Install system packages
    apt:
      name: ['pip', 'unzip', 'net-tools']
      force_apt_get: yes
      state: present

  - name: Install Ansible and AWS modules through pip3
    command: "{{ item }}"
    with_items:
      - pip3 install --upgrade pip
      - pip3 install ansible
      - pip3 install boto boto3
      - pip3 install ansible[aws]

  - name: Get Docker GPG key
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

  - name: Add Docker repo
    lineinfile:
      dest: /etc/apt/sources.list.d/docker.list
      line: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
      create: yes

  - name: Update repo list for Docker
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Install Docker
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'docker-compose-plugin', 'docker-scan-plugin', 'docker-ce-rootless-extras']
      force_apt_get: yes
      state: present

  - name: Add user to Docker group
    user:
      name: deploy
      groups: docker
      append: yes

  - name: Enable and start Docker service
    systemd:
      name: docker
      enabled: yes
      state: restarted
