---
- hosts: localhost
  become: yes
  gather_facts: false
  vars_files:
    - globals.yaml

  tasks:
    - name: Download 3rd-party pre-requisite packages
      shell: |
        curl -s -L github.com/carvel-dev/ytt/releases/download/v0.45.0/ytt-linux-amd64 > /tmp/ytt
        mv /tmp/ytt /usr/local/bin/ytt
        chmod +x /usr/local/bin/ytt
        curl -s -L github.com/carvel-dev/ytt/releases/download/v0.45.0/imgpkg-linux-amd64 > /tmp/imgpkg
        mv /tmp/imgpkg /usr/local/bin/imgpkg
        chmod +x /usr/local/bin/imgpkg
        curl -s -L github.com/carvel-dev/ytt/releases/download/v0.45.0/kbld-linux-amd64 > /tmp/kbld
        mv /tmp/kbld /usr/local/bin/kbld
        chmod +x /usr/local/bin/kbld
        curl -s -L github.com/carvel-dev/ytt/releases/download/v0.45.0/kapp-linux-amd64 > /tmp/kapp
        mv /tmp/kapp /usr/local/bin/kapp
        chmod +x /usr/local/bin/kapp
    
    - name: Install Kubernetes GPG key
      shell: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/kubernetes-xenial.gpg"
      
    - name: Create sources.list.d file for Kubernetes
      shell: "apt-add-repository \"deb http://apt.kubernetes.io/ kubernetes-xenial main\""
    
    - name: Update package cache in Ubuntu
      apt:
      update_cache: yes
      force_apt_get: yes

    - name: Install Kubernetes packages
      apt:
        name: ['kubectl']
        force_apt_get: yes
        state: present

    - name: Unpack Tanzu bundle from .tar file
      command: tar xvf /tmp/tanzu-cli-bundle-linux-amd64.tar -C /tmp/

    - name: Install Tanzu CLI
      command: install /tmp/cli/core/{{ version }}/tanzu-core-linux_amd64 /usr/local/bin/tanzu
      register: tanzu_install

    - name: Sync Tanzu Plugins
      command: tanzu plugin sync
      register: tanzu_plugin_sync

    - name: Initialize Tanzu
      command: tanzu init
      register: tanzu_init
